version: '3.7'
services:
  power-lines-web:
    build:
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./PowerLinesWeb:/home/dotnet/PowerLinesWeb
      - ./PowerLinesWeb.Tests:/home/dotnet/PowerLinesWeb.Tests
