version: '3.7'
services:
  power-lines-web:
    build:
      target: development
    ports:
      - "5000:5000"
    environment: 
      FixtureUrl__Endpoint: http://power-lines-fixtures-service:5001
    volumes:
      - ./PowerLinesWeb:/home/dotnet/PowerLinesWeb
      - ./PowerLinesWeb.Tests:/home/dotnet/PowerLinesWeb.Tests
