services:
  power-lines-web:
    build:
      target: development
    ports:
      - "5000:5000"
    environment: 
      FIXTUREURL__ENDPOINT: http://power-lines-fixture-service:5002
      ACCURACYURL__ENDPOINT: http://power-lines-accuracy-service:5001
    volumes:
      - ./PowerLinesWeb:/home/dotnet/PowerLinesWeb
    networks:
      - power-lines

networks:
  power-lines:
    driver: bridge
    name: power-lines
