version: '3.7'
services:
  power-lines-web:
    build:
      target: development
    ports:
      - "5000:5000"
      - "5001:5001"
    environment: 
      FixtureUrl__Endpoint: http://power-lines-fixture-service:5002
    volumes:
      - ./PowerLinesWeb:/home/dotnet/PowerLinesWeb
      - ./PowerLinesWeb.Tests:/home/dotnet/PowerLinesWeb.Tests
