services:
  power-lines-web:
    build:
      target: development
    ports:
      - "5000:5000"
    environment: 
      FixtureUrl__Endpoint: http://power-lines-fixture-service:5002
      AccuracyUrl__Endpoint: http://power-lines-accuracy-service:5001
    volumes:
      - ./PowerLinesWeb:/home/dotnet/PowerLinesWeb
      - ./PowerLinesWeb.Tests:/home/dotnet/PowerLinesWeb.Tests
    networks:
      - power-lines

networks:
  power-lines:
    driver: bridge
    name: power-lines
