{{- include "helm-library.cluster-ip-service" (list . "power-lines-web.cluster-ip-service") -}}
{{- define "power-lines-web.cluster-ip-service" -}}
{{- if .Values.ingress.host }}
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
{{- end }}
{{- end -}}
