// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerLinesWeb.Data;

#nullable disable

namespace PowerLinesWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerLinesWeb.Data.AccuracyCalibrationRecord", b =>
                {
                    b.Property<int>("AccuracyCalibrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("accuracyCalibrationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccuracyCalibrationId"));

                    b.Property<DateTime>("Calculated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculated");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("numeric")
                        .HasColumnName("lowerBound");

                    b.Property<decimal>("Observed")
                        .HasColumnType("numeric")
                        .HasColumnName("observed");

                    b.Property<decimal>("Predicted")
                        .HasColumnType("numeric")
                        .HasColumnName("predicted");

                    b.Property<int>("Predictions")
                        .HasColumnType("integer")
                        .HasColumnName("predictions");

                    b.Property<decimal>("UpperBound")
                        .HasColumnType("numeric")
                        .HasColumnName("upperBound");

                    b.HasKey("AccuracyCalibrationId");

                    b.HasIndex("Division", "LowerBound")
                        .IsUnique();

                    b.ToTable("accuracy_calibration");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.AccuracyRecord", b =>
                {
                    b.Property<int>("AccuracyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("accuracyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccuracyId"));

                    b.Property<decimal>("BaselineAccuracy")
                        .HasColumnType("numeric")
                        .HasColumnName("baselineAccuracy");

                    b.Property<decimal>("BrierScore")
                        .HasColumnType("numeric")
                        .HasColumnName("brierScore");

                    b.Property<DateTime>("Calculated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculated");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<decimal>("LogLoss")
                        .HasColumnType("numeric")
                        .HasColumnName("logLoss");

                    b.Property<int>("LowerRecommended")
                        .HasColumnType("integer")
                        .HasColumnName("lowerRecommended");

                    b.Property<decimal>("LowerRecommendedAccuracy")
                        .HasColumnType("numeric")
                        .HasColumnName("lowerRecommendedAccuracy");

                    b.Property<decimal>("MarketLogLoss")
                        .HasColumnType("numeric")
                        .HasColumnName("marketLogLoss");

                    b.Property<int>("Matches")
                        .HasColumnType("integer")
                        .HasColumnName("matches");

                    b.Property<int>("PricedMatches")
                        .HasColumnType("integer")
                        .HasColumnName("pricedMatches");

                    b.Property<int>("Recommended")
                        .HasColumnType("integer")
                        .HasColumnName("recommended");

                    b.Property<decimal>("RecommendedAccuracy")
                        .HasColumnType("numeric")
                        .HasColumnName("recommendedAccuracy");

                    b.Property<int>("ScoredMatches")
                        .HasColumnType("integer")
                        .HasColumnName("scoredMatches");

                    b.Property<int>("ValueBets")
                        .HasColumnType("integer")
                        .HasColumnName("valueBets");

                    b.Property<decimal>("ValueRoi")
                        .HasColumnType("numeric")
                        .HasColumnName("valueRoi");

                    b.Property<int>("ValueWins")
                        .HasColumnType("integer")
                        .HasColumnName("valueWins");

                    b.HasKey("AccuracyId");

                    b.HasIndex("Division")
                        .IsUnique();

                    b.ToTable("accuracy");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.Fixture", b =>
                {
                    b.Property<int>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fixtureId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FixtureId"));

                    b.Property<decimal>("AwayOddsAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("awayOddsAverage");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("text")
                        .HasColumnName("awayTeam");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<decimal>("DrawOddsAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("drawOddsAverage");

                    b.Property<decimal>("HomeOddsAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("homeOddsAverage");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("text")
                        .HasColumnName("homeTeam");

                    b.HasKey("FixtureId");

                    b.HasIndex("Date", "HomeTeam", "AwayTeam")
                        .IsUnique();

                    b.ToTable("fixtures");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.MatchOdds", b =>
                {
                    b.Property<int>("MatchOddsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matchOddsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchOddsId"));

                    b.Property<decimal>("Away")
                        .HasColumnType("numeric")
                        .HasColumnName("away");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("expectedAwayGoals");

                    b.Property<decimal>("AwayProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("awayProbability");

                    b.Property<DateTime>("Calculated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculated");

                    b.Property<decimal>("Draw")
                        .HasColumnType("numeric")
                        .HasColumnName("draw");

                    b.Property<decimal>("DrawProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("drawProbability");

                    b.Property<decimal>("ExpectedGoals")
                        .HasColumnType("numeric")
                        .HasColumnName("expectedGoals");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer")
                        .HasColumnName("fixtureId");

                    b.Property<decimal>("Home")
                        .HasColumnType("numeric")
                        .HasColumnName("home");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("expectedHomeGoals");

                    b.Property<decimal>("HomeProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("homeProbability");

                    b.Property<string>("LowerRecommended")
                        .HasColumnType("text")
                        .HasColumnName("lowerRecommended");

                    b.Property<string>("Recommended")
                        .HasColumnType("text")
                        .HasColumnName("recommended");

                    b.Property<decimal>("ValueEdge")
                        .HasColumnType("numeric")
                        .HasColumnName("valueEdge");

                    b.Property<decimal>("ValueOdds")
                        .HasColumnType("numeric")
                        .HasColumnName("valueOdds");

                    b.Property<string>("ValueSelection")
                        .HasColumnType("text")
                        .HasColumnName("valueSelection");

                    b.Property<decimal>("ValueStake")
                        .HasColumnType("numeric")
                        .HasColumnName("valueStake");

                    b.HasKey("MatchOddsId");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.ToTable("match_odds");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resultId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultId"));

                    b.Property<decimal>("AwayOddsAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("awayOddsAverage");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("text")
                        .HasColumnName("awayTeam");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<decimal>("DrawOddsAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("drawOddsAverage");

                    b.Property<int>("FullTimeAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("fullTimeAwayGoals");

                    b.Property<int>("FullTimeHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("fullTimeHomeGoals");

                    b.Property<string>("FullTimeResult")
                        .HasColumnType("text")
                        .HasColumnName("fullTimeResult");

                    b.Property<int>("HalfTimeAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("halfTimeAwayGoals");

                    b.Property<int>("HalfTimeHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("halfTimeHomeGoals");

                    b.Property<string>("HalfTimeResult")
                        .HasColumnType("text")
                        .HasColumnName("halfTimeResult");

                    b.Property<decimal>("HomeOddsAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("homeOddsAverage");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("text")
                        .HasColumnName("homeTeam");

                    b.HasKey("ResultId");

                    b.HasIndex("Date", "HomeTeam", "AwayTeam")
                        .IsUnique();

                    b.ToTable("results");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.ResultMatchOdds", b =>
                {
                    b.Property<int>("ResultMatchOddsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matchOddsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultMatchOddsId"));

                    b.Property<decimal>("Away")
                        .HasColumnType("numeric")
                        .HasColumnName("away");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("expectedAwayGoals");

                    b.Property<decimal>("AwayProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("awayProbability");

                    b.Property<DateTime>("Calculated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculated");

                    b.Property<decimal>("Draw")
                        .HasColumnType("numeric")
                        .HasColumnName("draw");

                    b.Property<decimal>("DrawProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("drawProbability");

                    b.Property<decimal>("ExpectedGoals")
                        .HasColumnType("numeric")
                        .HasColumnName("expectedGoals");

                    b.Property<decimal>("Home")
                        .HasColumnType("numeric")
                        .HasColumnName("home");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("expectedHomeGoals");

                    b.Property<decimal>("HomeProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("homeProbability");

                    b.Property<string>("LowerRecommended")
                        .HasColumnType("text")
                        .HasColumnName("lowerRecommended");

                    b.Property<string>("Recommended")
                        .HasColumnType("text")
                        .HasColumnName("recommended");

                    b.Property<int>("ResultId")
                        .HasColumnType("integer")
                        .HasColumnName("resultId");

                    b.Property<decimal>("ValueEdge")
                        .HasColumnType("numeric")
                        .HasColumnName("valueEdge");

                    b.Property<decimal>("ValueOdds")
                        .HasColumnType("numeric")
                        .HasColumnName("valueOdds");

                    b.Property<string>("ValueSelection")
                        .HasColumnType("text")
                        .HasColumnName("valueSelection");

                    b.Property<decimal>("ValueStake")
                        .HasColumnType("numeric")
                        .HasColumnName("valueStake");

                    b.HasKey("ResultMatchOddsId");

                    b.HasIndex("ResultId")
                        .IsUnique();

                    b.ToTable("result_match_odds");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.MatchOdds", b =>
                {
                    b.HasOne("PowerLinesWeb.Data.Fixture", null)
                        .WithOne("MatchOdds")
                        .HasForeignKey("PowerLinesWeb.Data.MatchOdds", "FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerLinesWeb.Data.ResultMatchOdds", b =>
                {
                    b.HasOne("PowerLinesWeb.Data.Result", null)
                        .WithOne("ResultMatchOdds")
                        .HasForeignKey("PowerLinesWeb.Data.ResultMatchOdds", "ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerLinesWeb.Data.Fixture", b =>
                {
                    b.Navigation("MatchOdds");
                });

            modelBuilder.Entity("PowerLinesWeb.Data.Result", b =>
                {
                    b.Navigation("ResultMatchOdds");
                });
#pragma warning restore 612, 618
        }
    }
}
