environment: production
name: power-lines-web
image: power-lines-web

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 250Mi
  limitCpu: 250m
  port: 5000
  comPlusEnableDiagnostics: 0
  fixtureEndpoint: http://power-lines-fixture-service
  accuracyEndpoint: http://power-lines-accuracy-service

ingress: {}

deployment: {}
