container:
  image: power-lines-web
  resourceTier: M
  port: 5000
  comPlusEnableDiagnostics: 0

configMap:
  environment: production
  fixtureEndpoint: http://power-lines-fixture-service
  accuracyEndpoint: http://power-lines-accuracy-service

ingress:
  host: powerlines.lynxmagnus.com

deployment: {}
